apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ APPNAME }}
  name: {{ APPNAME }}
  namespace: {{ NAMESPACE }}
spec:
  ports:
    - name: {{ APPNAME }}
      port: {{ SERVICEPORT }}
      protocol: TCP
  selector:
    app: {{ APPNAME }}
