apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ APPNAME }} 
  namespace: {{ NAMESPACE }}
spec:
  tls:
  - secretName: {{ SECRET }}
  rules:
  - host: {{ HOST }} 
    http:
      paths:
      - path: /{{ APPNAME }}/*
        backend:
          serviceName: {{ APPNAME }} 
          servicePort: {{ SERVICEPORT }} 
